version: '3.8'

services:
  app:
    build: .
    container_name: job-ts-be-v2
    network_mode: "host"
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRED_DAY: ${JWT_EXPIRED_DAY}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "5105:5105"