version: '3.8'

services:
  app:
    build: .
    container_name: job-ts-be-v2
    network_mode: "host"
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_CHANGE_SECRET: ${EMAIL_CHANGE_SECRET}
      INVITATION_SECRET: ${INVITATION_SECRET}
      JWT_EXPIRED_DAY: ${JWT_EXPIRED_DAY}
      EMAIL_CHANGE_EXPIRED_DAY: ${EMAIL_CHANGE_EXPIRED_DAY}
      PASSWORD_RESET_SECRET: ${PASSWORD_RESET_SECRET}
      PASSWORD_RESET_EXPIRED_DAY: ${PASSWORD_RESET_EXPIRED_DAY}
      INVITATION_DAY: ${INVITATION_DAY}
      FRONTEND_URL: ${FRONTEND_URL}
      SYSTEM_MAIL: ${SYSTEM_MAIL}
      SYSTEM_MAIL_PASSWORD: ${SYSTEM_MAIL_PASSWORD}
    ports:
      - "5105:5105"