server:
  port: ${SERVER_PORT}

spring:
  application:
    name: job.ts.be.v2
  data:
    mongodb:
      uri: ${MONGO_URI}
  servlet:
    multipart:
      enabled:true
      max-file-size:50MB
      max-request-size:100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SYSTEM_MAIL}
    password: ${SYSTEM_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*" # Tüm sertifikalara güvenmek için (Sadece geliştirme ortamı için önerilir)

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  invitation-secret: ${INVITATION_SECRET}
  email-change-secret: ${EMAIL_CHANGE_SECRET}
  expiredDay: ${JWT_EXPIRED_DAY}
  email-change-expiredDay: ${EMAIL_CHANGE_EXPIRED_DAY}
  invitation-expiredDay: ${INVITATION_DAY}

frontend:
  url: ${FRONTEND_URL}

email-change:
  cooldown-seconds: 60
  code-validity-minutes: 10
  token-validity-minutes: 15
