server:
  port: 8080



spring:
  application:
    name: job.ts.be.v2
  data:
    mongodb:
      uri: mongodb://root11:371root1124@localhost:27017/jobts_v2?authSource=admin
  servlet:
    multipart:
      enabled:true
      max-file-size:50MB
      max-request-size:100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: aygarcelalx@gmail.com
    password: jcvc drer cyfs gdia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*" # Tüm sertifikalara güvenmek için (Sadece geliştirme ortamı için önerilir)

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
              MongoTemplate: DEBUG
      mongodb:
        driver:
          protocol:
            command: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: "QWx3YXlzLXNlY3VyZS1hbmQtc3Ryb25nLWtleS1mb3Itam90LTUxMi1zZWN1cml0eS0xMjM0NTY3ODkwMTIzNDU2Nzg5"
  invitation-secret: "QWx3YXlzLXNlY3VyZS1hbmQtc3Ryb25nLWtleS1mb3Itam90LTUxMi1zZWN1cml0eS0xMjM0NTY3ODkwMTIzNDU2Nzg4"
  email-change-secret: "QWx3YXlzLXNlY3VyZS1hbmQtc3Ryb25nLWtleS1mb3Itam90LTUxMi1zZWN1cml0eS0xMjM0NTY3ODkwMTIzNDU2Nzg3"
  expiredDay: 1286400000

frontend:
  url: "http://localhost:5173/"